### ISSUE TITLE
Remove RFN

### ISSUE THREAD

**Issue by davelab6** [smc/Chilanka#6]
https://github.com/smc/Chilanka/blob/master/Chilanka.sfd#L6 has an RFN.

A reserved font name isn't a good idea for 2 reasons.

1. It makes the process of collaboration via github cumbersome; if a member
of the general public clicks the 'fork' button up top right, they must
either seek permission from you before-hand to use the RFN, or to
immediately change the font name in the files as part of their first
modification, and then you'll have to change it back.

2. Many websites who self host the font files will modify them, doing
subsetting and format conversion, which are both explicitly defined in the
OFL as kinds of modification subject to the RFN restriction. SIL have been
willing to offer their view that the most popular web font formats are not
format conversions subject to the RFN restriction, but popular web font
bundling service Font Squirrel includes the less popular formats too, which
do. And subsetting remains. So, changing the name or contacting you are
both administrative burdens for these downstream users, and if they do
contact you, for you; and many people won't think carefully about this and
will just do so without asking, which formally terminates their license.
Putting them in that position is not a good situation.

So not having any RFNs is my recommendation :)

**Comment by davelab6** [comment]
Ping :)

**Comment by jishnu7** [comment]
I'll ping the developers offline.

**Comment by rajeeshknambiar** [comment]
Hi Dave,

We (developer community) want to have a wider discussion to arrive at an agreement on RFN. Apologies for the delay, we're trying to have the dialogue within a reasonable time frame. Hope to post an update soon.

**Comment by davelab6** [comment]
No worries :) do you have a target date?

I am thinking of visiting Kerala in late July or early august. Are there
any typography or software freedom events at this time?

**Comment by anivar** [comment]
Hi Dave,

We can move visiting discussion to a mail thread . AFAIK , the decision to use RFN was for addressing the local context of many forks and feature table copying without respecting license and copyrights. I think we stabilized that local context now , and I believe , it can be revoked if all developers agrees . I dont see any blocker in  this aspect .

**Comment by davelab6** [comment]
Happy to move discussion to any list - perhaps http://groups.google.com/forum/#!forum/googlefonts-discuss ? :)

**Comment by santhoshtr** [comment]
Done in e6fd9fac2b8ffb5dde5e872f9d51c60818e78e43
