### ISSUE TITLE
FB Fails reported

### ISSUE THREAD

**Issue by vv-monsalve** [smc/Chilanka#8]
Hi @santhoshtr,

As part of Chilanka's updating process in GoogleFonts, after QA round with Fontbakery, the following Fails are reported:

<details><summary>🔥 <b>FAIL:</b> Check Google Fonts glyph coverage. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyph_coverage">com.google.fonts/check/glyph_coverage</a>)</summary><div>

>
>Google Fonts expects that fonts in its collection support at least the minimal set of characters defined in the `GF-latin-core` glyph-set.
>
* 🔥 **FAIL** Missing required codepoints:

	- 0x0308 (COMBINING DIAERESIS)

	- 0x0300 (COMBINING GRAVE ACCENT)

	- 0x0301 (COMBINING ACUTE ACCENT)

	- 0x030B (COMBINING DOUBLE ACUTE ACCENT)

	- 0x0304 (COMBINING MACRON)

	- 0x02D9 (DOT ABOVE)

	- 0x0102 (LATIN CAPITAL LETTER A WITH BREVE)

	- 0x01CD (LATIN CAPITAL LETTER A WITH CARON)

	- 0x0104 (LATIN CAPITAL LETTER A WITH OGONEK)

	- 0x0106 (LATIN CAPITAL LETTER C WITH ACUTE)

	- 0x010C (LATIN CAPITAL LETTER C WITH CARON)

	- 0x010A (LATIN CAPITAL LETTER C WITH DOT ABOVE)

	- 0x010E (LATIN CAPITAL LETTER D WITH CARON)

	- 0x0110 (LATIN CAPITAL LETTER D WITH STROKE)

	- 0x011A (LATIN CAPITAL LETTER E WITH CARON)

	- 0x0116 (LATIN CAPITAL LETTER E WITH DOT ABOVE)

	- 0x0112 (LATIN CAPITAL LETTER E WITH MACRON)

	- 0x0118 (LATIN CAPITAL LETTER E WITH OGONEK)

	- 0x011E (LATIN CAPITAL LETTER G WITH BREVE)

	- 0x0122 (LATIN CAPITAL LETTER G WITH CEDILLA)

	- 0x0120 (LATIN CAPITAL LETTER G WITH DOT ABOVE)

	- 0x0126 (LATIN CAPITAL LETTER H WITH STROKE)

	- 0x0132 (LATIN CAPITAL LIGATURE IJ)

	- 0x0130 (LATIN CAPITAL LETTER I WITH DOT ABOVE)

	- 0x012E (LATIN CAPITAL LETTER I WITH OGONEK)

	- 0x0136 (LATIN CAPITAL LETTER K WITH CEDILLA)

	- 0x0139 (LATIN CAPITAL LETTER L WITH ACUTE)

	- 0x013D (LATIN CAPITAL LETTER L WITH CARON)

	- 0x013B (LATIN CAPITAL LETTER L WITH CEDILLA)

	- 0x0141 (LATIN CAPITAL LETTER L WITH STROKE)

	- 0x0143 (LATIN CAPITAL LETTER N WITH ACUTE)

	- 0x0147 (LATIN CAPITAL LETTER N WITH CARON)

	- 0x0145 (LATIN CAPITAL LETTER N WITH CEDILLA)

	- 0x014A (LATIN CAPITAL LETTER ENG)

	- 0x0150 (LATIN CAPITAL LETTER O WITH DOUBLE ACUTE)

	- 0x014C (LATIN CAPITAL LETTER O WITH MACRON)

	- 0x0154 (LATIN CAPITAL LETTER R WITH ACUTE)

	- 0x0158 (LATIN CAPITAL LETTER R WITH CARON)

	- 0x0156 (LATIN CAPITAL LETTER R WITH CEDILLA)

	- 0x015A (LATIN CAPITAL LETTER S WITH ACUTE)

	- 0x0160 (LATIN CAPITAL LETTER S WITH CARON)

	- 0x015E (LATIN CAPITAL LETTER S WITH CEDILLA)

	- 0x0218 (LATIN CAPITAL LETTER S WITH COMMA BELOW)

	- 0x1E9E (LATIN CAPITAL LETTER SHARP S)

	- 0x0164 (LATIN CAPITAL LETTER T WITH CARON)

	- 0x021A (LATIN CAPITAL LETTER T WITH COMMA BELOW)

	- 0x016C (LATIN CAPITAL LETTER U WITH BREVE)

	- 0x0170 (LATIN CAPITAL LETTER U WITH DOUBLE ACUTE)

	- 0x0172 (LATIN CAPITAL LETTER U WITH OGONEK)

	- 0x016E (LATIN CAPITAL LETTER U WITH RING ABOVE)

	- 0x1E82 (LATIN CAPITAL LETTER W WITH ACUTE)

	- 0x0174 (LATIN CAPITAL LETTER W WITH CIRCUMFLEX)

	- 0x1E84 (LATIN CAPITAL LETTER W WITH DIAERESIS)

	- 0x1E80 (LATIN CAPITAL LETTER W WITH GRAVE)

	- 0x0176 (LATIN CAPITAL LETTER Y WITH CIRCUMFLEX)

	- 0x0178 (LATIN CAPITAL LETTER Y WITH DIAERESIS)

	- 0x1EF2 (LATIN CAPITAL LETTER Y WITH GRAVE)

	- 0x0179 (LATIN CAPITAL LETTER Z WITH ACUTE)

	- 0x017D (LATIN CAPITAL LETTER Z WITH CARON)

	- 0x017B (LATIN CAPITAL LETTER Z WITH DOT ABOVE)

	- 0x0103 (LATIN SMALL LETTER A WITH BREVE)

	- 0x01CE (LATIN SMALL LETTER A WITH CARON)

	- 0x0105 (LATIN SMALL LETTER A WITH OGONEK)

	- 0x0107 (LATIN SMALL LETTER C WITH ACUTE)

	- 0x010D (LATIN SMALL LETTER C WITH CARON)

	- 0x010B (LATIN SMALL LETTER C WITH DOT ABOVE)

	- 0x010F (LATIN SMALL LETTER D WITH CARON)

	- 0x0111 (LATIN SMALL LETTER D WITH STROKE)

	- 0x011B (LATIN SMALL LETTER E WITH CARON)

	- 0x0117 (LATIN SMALL LETTER E WITH DOT ABOVE)

	- 0x0113 (LATIN SMALL LETTER E WITH MACRON)

	- 0x0119 (LATIN SMALL LETTER E WITH OGONEK)

	- 0x011F (LATIN SMALL LETTER G WITH BREVE)

	- 0x0123 (LATIN SMALL LETTER G WITH CEDILLA)

	- 0x0121 (LATIN SMALL LETTER G WITH DOT ABOVE)

	- 0x0127 (LATIN SMALL LETTER H WITH STROKE)

	- 0x0133 (LATIN SMALL LIGATURE IJ)

	- 0x012F (LATIN SMALL LETTER I WITH OGONEK)

	- 0x0237 (LATIN SMALL LETTER DOTLESS J)

	- 0x0137 (LATIN SMALL LETTER K WITH CEDILLA)

	- 0x013A (LATIN SMALL LETTER L WITH ACUTE)

	- 0x013E (LATIN SMALL LETTER L WITH CARON)

	- 0x013C (LATIN SMALL LETTER L WITH CEDILLA)

	- 0x0142 (LATIN SMALL LETTER L WITH STROKE)

	- 0x0144 (LATIN SMALL LETTER N WITH ACUTE)

	- 0x0148 (LATIN SMALL LETTER N WITH CARON)

	- 0x0146 (LATIN SMALL LETTER N WITH CEDILLA)

	- 0x014B (LATIN SMALL LETTER ENG)

	- 0x0151 (LATIN SMALL LETTER O WITH DOUBLE ACUTE)

	- 0x014D (LATIN SMALL LETTER O WITH MACRON)

	- 0x0155 (LATIN SMALL LETTER R WITH ACUTE)

	- 0x0159 (LATIN SMALL LETTER R WITH CARON)

	- 0x0157 (LATIN SMALL LETTER R WITH CEDILLA)

	- 0x0161 (LATIN SMALL LETTER S WITH CARON)

	- 0x015F (LATIN SMALL LETTER S WITH CEDILLA)

	- 0x0219 (LATIN SMALL LETTER S WITH COMMA BELOW)

	- 0x0165 (LATIN SMALL LETTER T WITH CARON)

	- 0x021B (LATIN SMALL LETTER T WITH COMMA BELOW)

	- 0x016D (LATIN SMALL LETTER U WITH BREVE)

	- 0x0171 (LATIN SMALL LETTER U WITH DOUBLE ACUTE)

	- 0x0173 (LATIN SMALL LETTER U WITH OGONEK)

	- 0x016F (LATIN SMALL LETTER U WITH RING ABOVE)

	- 0x1E83 (LATIN SMALL LETTER W WITH ACUTE)

	- 0x0175 (LATIN SMALL LETTER W WITH CIRCUMFLEX)

	- 0x1E85 (LATIN SMALL LETTER W WITH DIAERESIS)

	- 0x1E81 (LATIN SMALL LETTER W WITH GRAVE)

	- 0x0177 (LATIN SMALL LETTER Y WITH CIRCUMFLEX)

	- 0x1EF3 (LATIN SMALL LETTER Y WITH GRAVE)

	- 0x017A (LATIN SMALL LETTER Z WITH ACUTE)

	- 0x017E (LATIN SMALL LETTER Z WITH CARON)

	- 0x017C (LATIN SMALL LETTER Z WITH DOT ABOVE)

	- 0x2122 (TRADE MARK SIGN)

	- 0x0307 (COMBINING DOT ABOVE)

	- 0x0302 (COMBINING CIRCUMFLEX ACCENT)

	- 0x030C (COMBINING CARON)

	- 0x0306 (COMBINING BREVE)

	- 0x030A (COMBINING RING ABOVE)

	- 0x0303 (COMBINING TILDE)

	- 0x0312 (COMBINING TURNED COMMA ABOVE)

	- 0x0326 (COMBINING COMMA BELOW)

	- 0x0327 (COMBINING CEDILLA)

	- 0x0328 (COMBINING OGONEK)

	- 0x02DD (DOUBLE ACUTE ACCENT)

	- 0x02D8 (BREVE)
 

	- And 0x02DB (OGONEK)
 [code: missing-codepoints]
</div></details>

The new GF Latin Core encoding was updated. Please let me know if you would be willing to cover the new required glyphs. Otherwise, I'll ask if we could ignore this Fail for Chilanka

----

<details><summary>🔥 <b>FAIL:</b> Check OFL body text is correct. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/license/OFL_body_text">com.google.fonts/check/license/OFL_body_text</a>)</summary><div>

>
>Check OFL body text is correct. Often users will accidently delete parts of the body text.
>
* 🔥 **FAIL** The OFL.txt body text is incorrect. Please use https://github.com/googlefonts/Unified-Font-Repository/blob/main/OFL.txt as a template. You should only modify the first line. [code: incorrect-ofl-body-text]
</div></details>

License URL should be `https://scripts.sil.org/OFL`

----

<details><summary>🔥 <b>FAIL:</b> Ensure dotted circle glyph is present and can attach marks. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/dotted_circle">com.google.fonts/check/dotted_circle</a>)</summary><div>

>
>The dotted circle character (U+25CC) is inserted by shaping engines before mark glyphs which do not have an associated base, especially in the context of broken syllabic clusters.
>
>For fonts containing combining marks, it is recommended that the dotted circle character be included so that these isolated marks can be displayed properly; for fonts supporting complex scripts, this should be considered mandatory.
>
>Additionally, when a dotted circle glyph is present, it should be able to display all marks correctly, meaning that it should contain anchors for all attaching marks.
>
* 🔥 **FAIL** The following glyphs could not be attached to the dotted circle glyph:

	- dotreph [code: unattached-dotted-circle-marks]
</div></details>

**Comment by santhoshtr** [comment]
>The new GF Latin Core encoding was updated. Please let me know if you would be willing to cover the new required glyphs. Otherwise, I'll ask if we could ignore this Fail for Chilanka

Please ignore this failure as there is no immediate plan to add those latin glyphs to Chilanka

> FAIL: Check OFL body text is correct. ([com.google.fonts/check/license/OFL_body_text](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/license/OFL_body_text))

Fixed this in https://gitlab.com/smc/fonts/chilanka/-/commit/296ef4bd7bca4ef65460eb00a220087b92886fd1

> FAIL: Ensure dotted circle glyph is present and can attach marks. ([com.google.fonts/check/dotted_circle](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/dotted_circle))

Fixed this in https://gitlab.com/smc/fonts/chilanka/-/commit/1f8cd2531f93a4262371e16aec0e1124c1cc50a4

New release: [Version 1.6](https://gitlab.com/smc/fonts/chilanka/-/releases/Version1.6)  has all these fixes.

**Comment by vv-monsalve** [comment]
Version 1.6 is live now.
